"""Add career_reports table

Revision ID: e3064333ce13
Revises: a349a18582ec
Create Date: 2026-07-30 18:19:39.442053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3064333ce13'
down_revision = 'a349a18582ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('marks_cgpa', sa.String(length=50), nullable=True),
    sa.Column('interests', sa.String(length=300), nullable=False),
    sa.Column('skills', sa.String(length=300), nullable=True),
    sa.Column('career_goal', sa.String(length=200), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('preferred_industry', sa.String(length=120), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_reports_user_id'))

    op.drop_table('career_reports')
    # ### end Alembic commands ###
